version: '3.4'

services:
  mysql:
    container_name: mysql_metegol
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/data/application/init.sql

  dev:
    container_name: metegol-project-dev
    build:
      context: .
      target: dev
    ports:
      - '8080:8080'
    environment:
      DB_USER: root
      DB_PASS: root
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: metegol_db

  prod:
    container_name: metegol-project-prod
    build:
      context: .
      target: prod
    ports:
      - '8080:8080'
    environment:
      DB_USER: root
      DB_PASS: root
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: metegol_db